### ISSUE TITLE
Images with broken links inside the ui-kit templates

### ISSUE THREAD

**Issue by dominikwilkowski** [AusDTO/dto-design-guide#116]
We got below files with broken links:

- `footer-navigation.html` _(The coat of arms should be on an absolute URL no?)_
- `lists-horizontal.html` _(All placeholders should be http://placehold.it images no?)_
- `lists-vertical.html` _(All placeholders should be http://placehold.it images no?)_

Will fix and push as a `hotfix`.

**Comment by klepas** [comment]
This is fixed; closing.
