### ISSUE TITLE
Reorganise Design Guide content into new IA

### ISSUE THREAD

**Issue by joolswood** [AusDTO/dto-design-guide#19]
As a user of the Design Guide I need it to be easy for me to locate the guidance I require.

- [x] Refactor all Foundations content into new template.
- [x] Refactor all Components content into new template.
- [x] Refactor all Patterns content into new template.
- [x] Refactor all Getting Started content into new templates.

**Comment by joolswood** [comment]
Initial task (underway) [mapping sections in spreadsheet](https://docs.google.com/spreadsheets/d/1C8LmNAkufaygI5kS9OIIPtpqkcILUebi__kXSg-4Z_Y/edit#gid=0).

**Comment by joolswood** [comment]
@joolswood to talk to @gazhands once scrape finished

**Comment by joolswood** [comment]
This is more related to the design tasks, but: we need to figure out how to set the order of sections in the local nav to override alphabetical. @klepas

**Comment by joolswood** [comment]
Just a little reminder for me that I've stashed a bunch for great resources on form design (mostly from Leisa) in the relevant JIRA ticket: https://govausites.atlassian.net/browse/DESIGN-475

**Comment by klepas** [comment]
Blocked by #24.

**Comment by joolswood** [comment]
Continuing to work in `feature/typography-refactor` for now (counter productive to create a new branch from this while we are still fixing template issues).

**Comment by klepas** [comment]
@joolswood Hey, can we split this issue up into smaller remaining items? (:

**Comment by joolswood** [comment]
@klepas I've edited the checklist to complete this task. The remainder work (until we agree to create tickets to write new stuff) is iteration of existing content. Should we / how do we ticket this?

**Comment by klepas** [comment]
> Should we / how do we ticket this?

The crit today? :)
