### ISSUE TITLE
Develop DOD process for Design Guide

### ISSUE THREAD

**Issue by joolswood** [AusDTO/dto-design-guide#23]
Resolve checklists git issues vs tickets

**Comment by gazhands** [comment]
Reviews
Code
Content
Design
Ally

**Comment by klepas** [comment]
@gazhands @joolswood Do we have these added to `.github/` folder as template files yet? :)

**Comment by klepas** [comment]
@dominikwilkowski Hey, we should finish this as I think it might help us work better. (:

**Comment by joolswood** [comment]
My bad, I just haven't got back to this. Happy to draft something, or work with you fine people.

**Comment by klepas** [comment]
@joolswood let’s just get a PR up together when you’re back — it’ll take us all of 5mins.

**Comment by klepas** [comment]
I’ve added PRs for both — see above. Please review. (:
