### ISSUE TITLE
Foundations: Typography Design Refactor

### ISSUE THREAD

**Issue by hannah-ustwo** [AusDTO/dto-design-guide#24]
Exploring and identify any necessary style/design updates to be made on this page (and as a template for the rest of the pages that sit under Foundations).

We're aiming to use as much of the existing UI kit as possible and not creating anything new unless it directly addresses our existing user research insights.

Attached is the Foundations template design completed by @gazhands
To be discussed with team:

- What in these designs are not in the UI-kit?
- What "new" design can/should we consider? What research does it tie back to?
- Any new tickets we should create to address design updates?

![image](https://cloud.githubusercontent.com/assets/19661064/20042940/145b2bc4-a4d7-11e6-980d-0362c1fe746c.png)

**Comment by hannah-ustwo** [comment]
Reviewing the current state of this page, and acknowledging the work being done on ausDTO/dto-design-guide#24, these are notes regarding any style changes on the pages:
- Divider lines to be added between elements/sections of a page. (refer to attached image)
- Style of visual example container to be updated  – new designs from @gazhands exist (refer to attached image),  I'm timebox-exploring other ways we can display visual examples + code as well.

**Comment by hannah-ustwo** [comment]
![image](https://cloud.githubusercontent.com/assets/19661064/20042701/d88337da-a4d2-11e6-99a2-bb8070ee4747.png)

**Comment by hannah-ustwo** [comment]
WIP:
Exploring different ways to present the visual example and code in a less clunky way, taking cues from @gazhands' existing designs...

![image](https://cloud.githubusercontent.com/assets/19661064/20042908/629e6dba-a4d6-11e6-9009-a180fa2105ba.png)

**Comment by joolswood** [comment]
Hey @hannah-ustwo I think in a lot of cases we'd want to show the code and example at the same time.

**Comment by joolswood** [comment]
A few things, based on today's work (all in `feature/typography-refactor`):

- [x] Major thing to fix is to have flexibility over how to order elements on the pages - so you don't need to edit the SASS to create/rename H2s and move guidance around.
- [x] The page principle (`Use clear and accessible typography as the primary way to communicate.` on Typography) should appear between the page title and the In the section menu.
- [x] I switched the syntax highlight to the light version. I don't know if this is as good as this: https://github.com/alphagov/govuk_elements/pull/338 @klepas ?
-  [x] We also need to change the blue below the code block.
-  [ ] Add GitHub icon to code reference link.
-  [x] Can we make the left and right borders visible on accordions? Kinda looks weird with just the bottom visible.
-  [x] The `abstract` class gives a bottom border. I've use an inline override (bad me) in the branch - can we discuss removing it completely from UI-Kit? I can't see a good semantic reason for always having a visible bottom border on `abstract` elements.
-  [x] Need to get the principle showing above the `In the section` and guidance in md below the example - @dominikwilkowski has made progress on this
- [ ] We'd like to get some component details defined in the SASS come across to the Design Guide ie a component description, a version, a browser support level and an accessibility support level.
  - [x] component description - let's discuss this with @klepas 
  - [x] a version (we can do this via `{% uikit_version %}` as the kit is not yet modular)
  - [ ] browser support level - parked for now
  - [ ] a11y support level - parked for now
- [ ] We'd like to implement tagging in a systematic way across Design Guide pages.
-  [x] Fix contrast of border on examples
-  [x] Need to append `DTA Design Guide` to the page title.
- [ ] Just playing around with improving the page headers after our chat @klepas - should we define a new style for this?
- [x] Change the md files to be named after the `title` not the `ID`

```
<h1><span style="font-size:0.5em; color:#6f777b;">DTO Design Guide</span><br />
  <span>{{ page.title }}</span></h1>
```
- [x] Reduce spacing between principle statement and `In this section` menu.
- [x] Reduce spacing between principle statement and Examples.

**Comment by joolswood** [comment]
Also there might be a fancy code way of generating the content of the `font-specimen.png`?

**Comment by joolswood** [comment]
Also contrast of border on examples

**Comment by hannah-ustwo** [comment]
TEMPORARY MESSAGE @joolswood @klepas can you guys get me the email to tommy at ICT in Sydney? Weve been booted off of DTA netwrks a bit too early...

**Comment by joolswood** [comment]
![screen shot 2016-11-11 at 2 38 15 pm](https://cloud.githubusercontent.com/assets/13774080/20203599/c5a63728-a81c-11e6-8803-0168d7f3a147.png)

Just playing around with improving the page headers after our chat @klepas - should we define a new style for this?

```
<h1><span style="font-size:0.5em; color:#6f777b;">DTO Design Guide</span><br />
  <span>{{ page.title }}</span></h1>
```

**Comment by joolswood** [comment]
Template mapping here: https://docs.google.com/spreadsheets/d/1Abn7vKhmrz8GA-DwwXniamD0lmgTI_KXCdntINny7Pc/edit#gid=0

**Comment by joolswood** [comment]
Hi @dominikwilkowski I've added a couple of missing things to the list above. This might be a problematic one we need to talk through with @klepas `We'd like to get some component details defined in the SASS come across to the Design Guide ie a component description, a version, a browser support level and an accessibility support level.`

**Comment by joolswood** [comment]
Hi @dominikwilkowski just querying the `The page principle (Use clear and accessible typography as the primary way to communicate. on Typography) should appear between the page title and the In the section menu.` being completed - I know it works for the H2s within the page, but how do we get content in `index.md` file to show up above the `In this section` menu on pages?

**Comment by joolswood** [comment]
Also re: @dominikwilkowski `Need to append DTA Design Guide to the page title.` - I meant appending `DTA Design Guide` within the <title> element of the page, can we do this?

**Comment by joolswood** [comment]
And just a couple of other things I spotted this arvo @dominikwilkowski :
- We need to name md files after the `ID` rather than the `Title` - should this be the other way around?
- I realised that the contents of Lists works better as a component of Typography than on it's own page in Foundation. In order to get this to work I had to edit the `_typography.scss` partial and the `templates/basic-links.html` files. I don't think there's any way we can get around me having to edit the SASS contents to do that kind of move. But not sure if, from a dev perspective, it's helpful to reference the links example in `_typography.scss` as well as in `_links.scss` - but I guess it doesn't hurt.

**Comment by dominikwilkowski** [comment]
Thanks @joolswood 

> how do we get content in `index.md` file to show up above the `In this section` menu on pages?

I need to talk to you about this. Not sure what the `In this section` section is :)

> I meant appending `DTA Design Guide` within the element of the page, can we do this?

You can add it to anything yourself or you tell me where and we add it to a bit inside the layout so it's automated and always there

> We need to name md files after the ID rather than the Title - should this be the other way around?

Very good point. Totally. I'm just a bit precious with file names. We can even add another attribute that takes the file name… ?

>  I don't think there's any way we can get around me having to edit the SASS contents to do that kind of move.

I'm not sure about that very workflow. Let's all have a chat about this on Monday and see. The constraints currently outweigh the benefits we get imho but I don't know enough yet to make decisions.

Happy weekend everyone ✊💥

**Comment by joolswood** [comment]
@dominikwilkowski 

> > how do we get content in index.md file to show up above the In this section menu on pages?
> > I need to talk to you about this. Not sure what the In this section section is :)

![screen shot 2016-11-21 at 8 58 21 am](https://cloud.githubusercontent.com/assets/13774080/20466505/b50702e0-afc8-11e6-9082-8d20b66fc861.png)

> > I meant appending DTA Design Guide within the element of the page, can we do this?
> > You can add it to anything yourself or you tell me where and we add it to a bit inside the layout so it's automated and always there

I have to explain this one over hangout I think. It's about how to add 'DTA Design Guide' into the `<title>` tag without changing the front matter of the md file.

> > We need to name md files after the ID rather than the Title - should this be the other way around?
> > Very good point. Totally. I'm just a bit precious with file names. We can even add another attribute that takes the file name… ?

Yah let's have a chat about this one.

> >  I don't think there's any way we can get around me having to edit the SASS contents to do that kind of move.
> > I'm not sure about that very workflow. Let's all have a chat about this on Monday and see. The constraints currently outweigh the benefits we get imho but I don't know enough yet to make decisions.

I might have to do a few more pages and figure out if it's too convoluted. It's not _too_ difficult yet.

**Comment by joolswood** [comment]
Gotta test out the `component description` and `version` too - let's talk about them also.

**Comment by klepas** [comment]
The remaining open checkbox items above have been pulled out to #39.

Gonna close this.
