### ISSUE TITLE
home page accessibility section

### ISSUE THREAD

**Issue by AndrewArch** [AusDTO/dto-design-guide#27]
1. Currently we say `UI Kit aims to be WCAG2 AA compliant, and AAA where possible.`
I suggest instead `UI Kit aims to be WCAG2 AA compliant, and AAA where appropriate.` as some AAA criteria are possible but not always appropriate as by lifting the level for some you can actually disadvantage others.

2. Rather than calling out `WAVE` as the manual evaluation tool, let' say `We are working on:  manual evaluation using a variety of tools`

**Comment by klepas** [comment]
Agreed. I will be updating this content, which is now under *Getting started* > *For developers* > *Accessibility*.

I’ll run the edits past you as part of issue #58.

Closing this ticket as a result.
