### ISSUE TITLE
Federated design team

### ISSUE THREAD

**Issue by gazhands** [AusDTO/dto-design-guide#3]
Federated design team structure. How does this work across the DTA teams? What does the process look like?

**Comment by klepas** [comment]
As with #4, bumping this — any extra info @gazhands ?

**Comment by hannah-ustwo** [comment]
Now in the strategy doc for exec review . Moving to done.

**Comment by gazhands** [comment]
Create lane in waffle (Federated design clinic)

**Comment by joolswood** [comment]
Hey @gazhands probably `gov-au-ui-kit` is the most appropriate repo to use for the swim lane?

**Comment by gazhands** [comment]
@joolswood wouldn't allow me to create the lane due to not being able to create a label?

**Comment by gazhands** [comment]
Done
