### ISSUE TITLE
Left over template and QA work post-Typography refactor

### ISSUE THREAD

**Issue by klepas** [AusDTO/dto-design-guide#39]
These are uncompleted tasks from #24.

- [x] Remove duplicate list of section child items (made redundant by local-nav) in collection overview/index pages.
- [x] Move any inline CSS styling into the `design-guide.scss` partial (eg the page h1 span styling).
- [x] Remove redundant scss in `design-guide.scss`
- [x] breadcrumbs
- [x] Add back to top link into the footer
- [x] reference `#h2-title` hovers and/or cites for the each `h2` in the documentation?
- [x] copy html eg to clipboard (clipboard.js?)
- [x] back to top links potentially for each `h2` in the documentation?
- [x] Add GitHub icon to code reference link.

**Comment by joolswood** [comment]
Just added a couple of things.

**Comment by klepas** [comment]
Note to self: agreed in sprint planning to split this into the stuff we wanna do, and the stuff we wanna do later. I’ll split these out.

**Comment by klepas** [comment]
New goodies in https://github.com/AusDTO/dto-design-guide/pull/54 that should provide for some of the remaining above checklist items. (:

**Comment by klepas** [comment]
I’ve started a branch on the *Home page custom layout* task.

**Comment by klepas** [comment]
Hey @dominikwilkowski what do you reckon — split this task up into what’s left and close this?

**Comment by klepas** [comment]
Hey all,

I’ve lifted out the remaining tasks, creating new issues for them, and tried to ID what’s blocked:

Lifted out:

- re-add the GH code line # reference URI. - broken link currently?
- favicon? ^_^
- Home page custom layout
- tagging #63

Leaving till later:

- Add in section name to the CSS styling above child pages — I added a branch that implements this: https://github.com/AusDTO/dto-design-guide/tree/feature/adds-section-name-to-section-h1s

Blocked:

- [ ] We'd like to get some component details defined in the SASS come across to the Design Guide ie a component description, a version, a browser support level and an accessibility support level.
  - [ ] browser support level - parked for now
  - [ ] a11y support level - parked for now

These are blocked because they rely on a range of edits to the UI-Kit.

**Comment by klepas** [comment]
Closing issue.
