### ISSUE TITLE
Add syntax highlighting for inline code

### ISSUE THREAD

**Issue by joolswood** [AusDTO/dto-design-guide#57]
Can you please show me how best to implement this @klepas?

**Comment by klepas** [comment]
I’m have a crack, and I’ll show you :)

**Comment by klepas** [comment]
I’ll give you the syntax for it, once I complete #67.

**Comment by klepas** [comment]
Hey @joolswood,

My PR #80 should cater for this.

For reference the method for invoking syntax highlighting for shell/terminal commands (bash or whatever other language) is as follows:

```
{% highlight shell %}
foo --bar
{% endhighlight %}
```

To do HTML highlighting use:

```
{% highlight html %}
<p>Some html!</p>
{% endhighlight %}
```

So in effect we’re replacing the backticks (`) with this highlight liquid tag. If you omit the language it will just set it as if it were a generic code block.

For a full list of the languages that the highlighter we’re using [rouge] support see: https://github.com/jneen/rouge/wiki/List-of-supported-languages-and-lexers
