### ISSUE TITLE
For developers content

### ISSUE THREAD

**Issue by joolswood** [AusDTO/dto-design-guide#58]
Edit content in https://github.com/AusDTO/dto-design-guide/tree/feature/typography-refactor/_getting-started/developers to:

- [x] remove stuff that should be in UI-Kit repo
- [x] update accessibility table and add to page
- [x] update browser support table and add to page

Thanks @klepas

**Comment by klepas** [comment]
I’ll pick this up today.

**Comment by klepas** [comment]
PR for this issue above for you @joolswood
