### ISSUE TITLE
Implement the homepage layout

### ISSUE THREAD

**Issue by klepas** [AusDTO/dto-design-guide#59]
This has been split out from https://github.com/AusDTO/dto-design-guide/issues/39

Work remaining:

- [x] hero design
- [ ] FAQ section — chat with Jools re. this section
- [ ] license & credit content — maybe move off the homepage?

**Comment by klepas** [comment]
Todos:

1. Chat to jools re. FAQ and licensing section
2. If we agree to move these out of the homepage, create separate tickets for them.

**Comment by gazhands** [comment]
![design guide - home](https://cloud.githubusercontent.com/assets/17328069/21084505/c6b744be-c058-11e6-8689-8da893d49be8.png)
