### ISSUE TITLE
Typography improvements (UI-Kit update)

### ISSUE THREAD

**Issue by gazhands** [AusDTO/dto-design-guide#69]
Address type sizes used, headers vs body copy (Foundations>layout seems pretty close) — happy to do this within UI-Kit after the DG 2.0 release.

**Comment by klepas** [comment]
@gazhands Agreed.

We could in theory override some of the typographic styling within the design guide stylesheet, and then push those edits upstream into UI-Kit, or we could just do it directly in UI-Kit later.

Your call.

**Comment by klepas** [comment]
@gazhands Hey, could you outline what needs to be done here? :)

**Comment by klepas** [comment]
Closing this.

The changes should be made upstream, in the UI-Kit.

Found an old (open) ticket from Alz on this: https://github.com/AusDTO/gov-au-ui-kit/issues/251
