### ISSUE TITLE
Accordion appearance and states (open v closed)

### ISSUE THREAD

**Issue by gazhands** [AusDTO/dto-design-guide#70]
Iterate on how we display a Component/Pattern
Example in box only
Use of borders and colours in accordions
Accordion states, open v closed

**Comment by klepas** [comment]
Thanks.

I’m assigning this one to you Dom, since you’re issue-less right now :D

**Comment by dominikwilkowski** [comment]
Adding design assets:

![0c45eaf0-b887-11e6-89f9-3ad154a91aa8](https://cloud.githubusercontent.com/assets/1266923/20994552/36d2c654-bd45-11e6-9e28-426e4af36a35.png)
![0c185392-b887-11e6-913d-698ff32c9185](https://cloud.githubusercontent.com/assets/1266923/20994553/38798f88-bd45-11e6-98c6-7216d512883e.png)

**Comment by klepas** [comment]
@gazhands @dominikwilkowski are we OK in retaining the copy to html button + the GH source reference *outside* the accordion?
