### ISSUE TITLE
Explain relationship between Foundations, Components, Patterns & Templates

### ISSUE THREAD

**Issue by joolswood** [AusDTO/dto-design-guide#81]
To include a version of this on each overview page.

**Comment by klepas** [comment]
Gaz posted these into slack after the meeting:

![pasted image at 2016_12_08 01_38 pm](https://cloud.githubusercontent.com/assets/52766/21035570/28209ce2-be14-11e6-8951-ac3bbbaa95ea.png)

![pasted image at 2016_12_08 01_39 pm](https://cloud.githubusercontent.com/assets/52766/21035578/3a4cfc4e-be14-11e6-8178-45d860a0492c.png)

![pasted image at 2016_12_08 01_39 pm 1](https://cloud.githubusercontent.com/assets/52766/21035589/4d41fd5e-be14-11e6-8b93-b62172da8501.png)

![pasted image at 2016_12_08 01_40 pm](https://cloud.githubusercontent.com/assets/52766/21035596/5436abb4-be14-11e6-8f17-d63322d404fb.png)

![pasted image at 2016_12_08 01_41 pm](https://cloud.githubusercontent.com/assets/52766/21035606/5d78dabc-be14-11e6-95f4-220f0a09a005.png)

**Comment by joolswood** [comment]
I tried a number of different ways to doing this but decided to delete them.

See this commit https://github.com/AusDTO/dto-design-guide/commit/9bbf7ac4389e71ee838e2870d7b95b7701e8c2ae#diff-0d1c9e3ca3e2b0521d25454a56423af0

If we have to explain how our IA works (which this was effectively trying to do) then the IA doesn't work.

I tried a lot of different ways to display it, but it always ended up looking like it would be too confusing for a user scanning the section overview page and seeing links to the other sections.

I did retain the words in the Getting started overview page.

I'd recommend against trying to explain other sections in another section's overview pages (see: it's confusing even trying to explain what we're doing! :)

Let's do some TreeJack tests and see how real users go with the IA.

**Comment by klepas** [comment]
Thanks for the update. I didn’t get around before you left, but had some thoughts I wanted to share:

> If we have to explain how our IA works (which this was effectively trying to do) then the IA doesn't work.

I’m almost entirely on-board—

We went from building a style guide to building a design system. The system has a structure that is not — imho — going to be apparent to many people (the relationships that foundations have, feeding into components, which in turn are the building blocks for patterns), not even necessarily front-end developers, or other implementers (as we have ascertained, not all implementers will have the level of experience we originally presumed they would have).

So, in part for much the same reasons that we all have come to agree that redundancy can be quite an advantageous thing, I feel like spelling this out succinctly has benefits.

FWIW, IMHO you’ve actually achieved this! I like the definitions you’ve given, and I like how you’ve adapted them contextually as one-liners as abstracts at the head of each section. (:

My only take now is to switch the *Get started* list of definitions into a definition list, which I think also makes the page far more scannable:

![getting-started-dls](https://cloud.githubusercontent.com/assets/52766/21415581/596a1f44-c85f-11e6-92d9-a982282aef10.png)

cf. http://guides.service.gov.au/design-guide/getting-started/index.html

What do you reckon? :)

**Comment by AndrewArch** [comment]
Agree - @joolswood has done a good job. And yes to "switch the Get started list of definitions into a definition list, which I think also makes the page far more scannable" @klepas

**Comment by klepas** [comment]
@AndrewArch I’m going to make a quick PR for this now.

**Comment by joolswood** [comment]
Closing this - should be able to delete `feature/getting-started-sections-dl` too @klepas
