### ISSUE TITLE
Typography page content improvements

### ISSUE THREAD

**Issue by joolswood** [AusDTO/dto-design-guide#83]
- [x] Why we picked Open Sans font family (in guidance)
- [ ] Headings - advise not to skip a level.
- [ ] Why h4-h6 styled same / govclass

**Comment by klepas** [comment]
Why we picked it is in the guidance already:

> Open Sans is a sans-serif font selected for accessibility and readability.

**Comment by joolswood** [comment]
I think the need was for greater specificity eg. what is it about sans-serif that makes it accessible. I'll hold off working on this until we have your branch merged.

**Comment by klepas** [comment]
> I think the need was for greater specificity eg. what is it about sans-serif that makes it accessible

@joolswood It can be easier to read than serif for some people (whereas serif can also be easier to read, depending on the serif…). San-serifs also did traditionally better when mapped to a pixel grid than serifs did.

Gaz might have more to add?

**Comment by joolswood** [comment]
I bookmarked this last week http://alexpoole.info/blog/which-are-more-legible-serif-or-sans-serif-typefaces/ it looks to be a pretty comprehensive overview. Are you aware of that research about screen vs print (his conclusion was there isn't a difference in legibility)? @klepas @AndrewArch

**Comment by joolswood** [comment]
I'd be inclined to leave it as is for now.
