### ISSUE TITLE
Fix Basic table errors

### ISSUE THREAD

**Issue by joolswood** [AusDTO/dto-design-guide#91]
- [x] Fix 'Poplulation'!!!
- [x] add unit

**Comment by joolswood** [comment]
Done. But wiill have to merge the example file into UI-Kit separately.

**Comment by klepas** [comment]
> But wiill have to merge the example file into UI-Kit separately.

@joolswood Gimme a copy and I can do it. (:

**Comment by joolswood** [comment]
Thanks. Slacking it to you.
