### ISSUE TITLE
Better define project & content licensing & disambiguate it from branding/logos

### ISSUE THREAD

**Issue by klepas** [AusDTO/dto-design-guide#97]
We’ve discussed the licensing notice in the footer, and link to the MIT license md file on GitHub…

I also just noticed that we make a singular license association, which is quite arguably understandable as applying to everything.

We should note that the Aus gov and Dg logo are reserved branding rights.

I think we should also amend the MD file to be in sync with the site footer msg in name, viz., Commonwealth of Australia (still says DTO).

Thoughts?

license md file: https://github.com/AusDTO/dto-design-guide/blob/master/LICENSE.md

**Comment by klepas** [comment]
@AndrewArch …aaaand we also don’t give any accessibility info… although I guess on the design guide site it’s kinda implied… but I reckon we should put them into the footer we want to distribute in the generic guide template theme anyway… (eg. an accessibility footer notice in the content guide’s footer). What do you think?

**Comment by joolswood** [comment]
Can work with you on this tomorrow @klepas ?

**Comment by klepas** [comment]
I made some edits to the `README.md` and `LICENSE.md` file for both repos that updates the copyright attribution from the DTO/A to the Commonwealth of Australia after confirming this with Cath Edwards.

We should still clearly state that the gov’t crest branding is all rights reserved (and no licensed MIT… which raises the Q: *what license* (if any?) is the crest licensed under?).

**Comment by AndrewArch** [comment]
maybe we model the copyright statement on what's used on http://www.finance.gov.au/publications/nts-2010-baseline-report/ or more recently http://www.finance.gov.au/publications/portfolio-budget-statements/16-17/

**Comment by AndrewArch** [comment]
and link "Commonwealth Coat of Arms" to http://www.dpmc.gov.au/government/commonwealth-coat-arms

**Comment by klepas** [comment]
Thanks @AndrewArch.

PR up.
